---
title: "Course code of conduct"
bibliography: BIFXgeneral.bib
---

This code of conduct applies to bioinformatics courses taught at Hood College.


## Academic Honor Code

Students are obligated to uphold principles of honesty, responsibility, and intellectual integrity in all activities related to their Hood College experience. The Academic Honor Code — a subset of the Code of Conduct — outlines expectations for student academic behavior and prohibits cheating and unauthorized assistance, plagiarism, resubmission of duplicate work, and other forms of academic dishonesty. Students should review the full Academic Honor Code located in Appendix B of the [Student Handbook](https://www.hood.edu/media/52921). Students should always consult with instructors to determine what types of aid are permitted in each specific class and on each assignment.

Faculty have authority to investigate alleged violations and issue sanctions. For unintentional plagiarism or similar violations, a sanction of a zero on the assignment is usually appropriate. For intentional plagiarism, cheating, and similar violations, failure of the course is a reasonable sanction. Faculty are required to report all violations to the Chair of the Academic Judicial Council (AJC), the Dean of Student Success. AJC will conduct hearings for students with egregious and/or multiple violations to determine if additional sanctions beyond those imposed by the instructor are warranted, including Suspension from the College.

### Reusing code

Unless explicitly stated otherwise, you may make use of online resources (e.g. StackOverflow) for coding examples on assignments and exams. If you directly use code from an outside source (or use it as inspiration), you must explicitly cite where you obtained the code. Any recycled code that is discovered and is not explicitly cited will be treated as plagiarism.

### Use of artificial intelligence (AI)

You should treat AI tools, such as ChatGPT, the same as other online resources. There are two guiding principles that govern how you can use AI in this course:

* Cognitive dimension: Working with AI should not reduce your ability to think clearly. AI should be used to facilitate, rather than hinder, learning.

* Ethical dimension: Students using AI should be transparent about their use and make sure it aligns with academic integrity. The ICMJE recommendations suggest, for example, that authors should explicitly acknowledge how they used AI in their work, but that the AI tool should not be included as an author, since it is neither accountable nor able to reliably check it's work [@icmje_recommendations_2025].

  * AI tools for code: You may make use of the technology for coding examples on assignments; if you do so, you must explicitly cite where you obtained the code. Any recycled code that is discovered and is not explicitly cited will be treated as plagiarism. You may use these guidelines for citing AI-generated content.
  * No AI tools for narrative: Unless instructed otherwise, AI is not permitted for writing narrative on assignments. In general, you may use AI as a resource as you complete assignments but not to answer the exercises for you. You are ultimately responsible for the work you turn in; it should reflect your understanding of the course content.

See the [Hood College's library website](https://hood.libguides.com/citation/AI) for more information on AI use and citation. If you are unsure if the use of a particular resource complies with the academic honesty policy, please reach out to Dr Johnson with any questions.


## Hood College aims to provide a supportive, collegial, and harassment-free environment

Hood College is dedicated to providing a supportive, collegial, and harassment-free experience for everyone, regardless of: 

* gender, gender identity and expression, sexual orientation, disability, physical appearance, body size, race, age, or religion.
* intellectual position: approaches to data analysis, software preferences, coding style, scientific perspective, etc.

This code of conduct, as well as the Hood College Code of Conduct and the Academic Honor Code, applies to all course-related communications, including but not limited to Blackboard, GitHub, the BIFX cluster, lectures, coding demos, labs, class time, group discussion, other Microsoft products and any other discussions related to BIFX 504. We do not tolerate harassment, intimidation, or bullying of students or staff. Sexual language and imagery are not appropriate in communications or in online venues, including chats.

Violating these rules will be dealt with according to the procedures outlined in the [Student Handbook](https://www.hood.edu/media/52921).

### Examples of unacceptable harassment, intimidation, and bullying behavior

Harassment includes, but is not limited to:
    
* Making comments in chats, to an audience or personally, that belittle or demean another person
* Sharing sexual images online
* Harassing photography or recording
* Sustained disruption of talks or other events
* Unwelcome sexual attention
* Advocating for, or encouraging, any of the above behavior

Intimidation and bullying include, but are not limited to:
    
* Aggressive or browbeating behavior directed at someone during a public presentation
* Mocking or insulting another person’s intellect, work, perspective, or question/comment
* Making reference to someone’s gender, gender identity and expression, sexual orientation, disability, physical appearance, body size, race, age, religion, or other personal attributes in the context of a scientific discussion
* Deliberately making someone feel unwelcome


## Social media policy

Images and content from lectures, labs, coding demos and class discussions may be shared publicly through social media or other public forums unless the instructor asks for it not to be. Homework and exams should not be shared or discussed outside of the course forums.


## Enforcement

Individuals asked to stop any harassing behavior are expected to comply immediately.

If an individual engages in harassing behavior, the instructor and/or other staff within the program will work with the offender to remediate the behavior. This includes warning the offender or possibly taking other academic actions.

The instructor may take action to redress anything designed to, or with the clear impact of, disrupting the course or making the environment hostile for any individuals.

We expect everyone to follow these rules throughout the course and during all course-related online activities.

## Reporting

If someone makes you or anyone else feel unsafe or unwelcome, please report it as soon as possible. Harassment and other code of conduct violations reduce the value of our program for everyone. We want to foster a safe, enjoyable and productive learning environment. People like you make our program better.

You can make a report either personally or anonymously.


### Anonymous or Non-anonymous Report

You can make an anonymous or non-anonymous report [here](https://www.hood.edu/node/9221). We can’t follow up an anonymous report with you directly, but we will fully investigate and do our best to prevent a recurrence.


### Personal Report

You can make a personal report with Dr Johnson or any other faculty member.

When taking a personal report, we will do our best to maintain your safety and privacy. We may involve other department staff to ensure your report is managed properly. Once safe, we’ll ask you to tell us about what happened. This can be upsetting, but we’ll handle it as respectfully as possible, and you can include someone to support you. You won’t be asked to confront anyone, but there are some incidents that we are required by law to report (i.e. in the case of sexual misconduct or when an individual's safety is at risk). We will do our best to maintain your anonymity when addressing the incident within the bounds of these laws. In the event that remediation may expose your identity, we will discuss options with you prior to taking any action.

We will be happy to help you contact campus security, local law enforcement, local support services, or otherwise assist you to feel safe. If you wish to speak with someone outside of Hood faculty, you can contact the Dean of the Chapel ([chapel\@hood.edu](mailto:chapel@hood.edu)), counseling services ([counselingservices\@hood.edu](mailto:counselingservices@hood.edu), or health services ([healthservices\@hood.edu](mailto:healthservices@hood.edu).


### Code of Conduct violation reports

* Discrimination, harassment and misconduct can be reported [here](https://www.hood.edu/node/9221).


## References

