---
title: Biopi
date: June 3, 2026
---

Biopi is a light-weight cluster that we will use to practice working on a high performance cluster, courtesy of Rho Analytics. The cluster is under active development right now. As a result, this page will receive significant updates in the near future.

## Setting up your account and logging in

To set up your account, you'll need an ssh key pair and some software on your computer. These steps will need to be completed for each computer you want to log in from, with the exception of emailing Dr Johnson your public key. You can copy your public key into `~/.ssh/authorized_keys` on Biopi yourself to grant access from new devices.

### ssh key pair

You can create your key pair in the terminal window with the following:

``` bash
ssh-keygen -t ed25519 -C "your_email@hood.edu"
```

Save it in the default location (`~/.ssh/`) and pick a passphrase if desired. The passphrase is optional, but it will allow anyone to use the key if they have access to it. If the `.ssh/` directory doesn't already exist in your home directory, you'll need to create it before this will work.

When you have your key, email your public key (i.e. `~/.ssh/id_ed25519.pub`) to Dr Johnson for account setup. You will receive an email confirming your account creation.

### Cloudflare

Logins are run through Cloudfare, so you'll also need to install a helper tool on your computer. Start by opening your local laptop's terminal or PowerShell and install the tool:

-   Mac (via Homebrew): `brew install cloudflared`
-   Windows (via winget): `winget install Cloudflare.cloudflared`
-   Linux: `sudo apt install cloudflared`

Once you have done this, remember to restart your terminal before trying to log in for the first time (which includes restarting the entire Positron app if you are working there).

You'll also need to add/edit your ssh config file so it knows to connect through Cloudflare. You can find your ssh config file at:

-   Mac/Linux Path: `~/.ssh/config`
-   Windows Path: `C:\Users\YourUsername\.ssh\config`

Open or create the config file (e.g. with `nano ~/.ssh/config`) and add this routing rule to the end of the file:

```         
Host biopi.rho-analytics.com
    ProxyCommand cloudflared access ssh --hostname %h
```

### Logging in

Once your account is created and your computer is set up properly, you should be able to log in with the following command:

``` bash
ssh username@biopi.rho-analytics.com
```

where "username" is your biopi user name. This will automatically open a browser window on Cloudflare, which will prompt you to confirm your identity using your Hood email. This authentication will need to be renewed after 24 hours.

## Modules

Biopi uses LMOD to manage different versions of some bioinformatics tools you might need. To check what has been installed, use

``` bash
module avail
```

and you can load a module and make it available for you to use with

``` bash
module load module_name
```

For eaxample, if you wanted to load `samtools` you would use

``` bash
module load samtools
```

By default the most recent version will be loaded, but if you prefer, you can specify an alternate version as follows:

``` bash
module load samtools/1.23.1
```

The following table lists the installed modules and versions as of June 3, 2026. If there is something you would like installed, contact Dr Johnson.

| Application | Versions |
|-------------|----------|
| BCFtools    | 1.23.1   |
| bedtools    | 2.31.1   |
| FastQC      | 0.12.1   |
| Python      | 3.14.5   |
| R           | 4.6.0    |
| samtools    | 1.23.1   |
| snakemake   | 9.22.0   |